[analyzer]
#source = "Alteryx"
source = "Knime"

[logging]
level="DEBUG"

[file_watch]
paths = [
    #'c:\git\analytics_pilot\tests\data',
    'C:\git\EuCalc\dev\tests\rust_test',
]

#patterns = ['*.yxmc', '*.yxmd', '*.yxwz']
patterns = ['*.knime', '*.xml']

